resolve conflict

diff --git a/bin/lnk b/bin/lnk
--- a/bin/lnk
+++ b/bin/lnk
@@ -1,6 +1,7 @@
 #!/bin/bash
 LOCAL_CONFIG="$HOME/.vanityURLs.conf"
 STATIC_FILE="static.lnk"
+MAX_ATTEMPTS=100
 
 function print_usage() {
   echo "There are two valid ways to call this script:"
@@ -27,7 +28,6 @@ function generate_shortcode() {
   done
 
   # Check if "/$random_string is already in the file
-  MAX_ATTEMPTS=100
   counter=0  # Initialize the counter
   while [ "$counter" -le $MAX_ATTEMPTS ]; do
     if grep -q "^/$random_string" "$STATIC_FILE"; then
@@ -35,12 +35,6 @@ function generate_shortcode() {
     else
       echo $random_string
       break
-    fi
-    if [ "$counter" -eq $MAX_ATTEMPTS ]; then
-      echo "Error: $MAX_ATTEMPTS attempts were made to find a unique
-      random string for your URL in $STATIC_FILE, aborting. Consider
-      raising the value of SHORTCODE_LENGTH in '$LOCAL_CONFIG'."
-      exit 1
     fi
   done
 }
@@ -55,6 +49,7 @@ fi
 
 # Expand REPO_DIR in case it starts with '~/'
 eval REPO_DIR=$REPO_DIR
+cd $REPO_DIR
 
 case "$#" in
   0)
@@ -63,10 +58,19 @@ case "$#" in
   1)
     LONG_URL="$1"
     SHORTCODE=$(generate_shortcode)
+    if [ "$SHORTCODE" = "" ]; then
+      echo "Error: $MAX_ATTEMPTS attempts were made to find a unique random string for your URL in $STATIC_FILE, but no success.
+      Aborting. Consider raising the value of SHORTCODE_LENGTH in '$LOCAL_CONFIG'."
+      exit 1
+    fi
     ;;
   2)
     LONG_URL="$1"
     SHORTCODE="$2"
+    if grep -q "^/$SHORTCODE" "$STATIC_FILE"; then
+      echo "Error: /$SHORTCODE is already taken in $STATIC_FILE."
+      exit 1
+    fi
     ;;
   *)
     print_usage
